version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/:/data
    restart: always

  spring:
    container_name: spring
    image: yundol/tangsquad
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_PORT=${SPRING_REDIS_PORT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - COOLSMS_API_KEY=${COOLSMS_API_KEY}
      - COOLSMS_API_SECRET=${COOLSMS_API_SECRET}
      - PHONE=${PHONE}
    volumes:
      - /var/log/:/logs/
    depends_on:
      - redis
