version: "3.7"
services:
  h2db:
    image: oscarfonts/h2:latest
    container_name: h2db
    ports:
      - 9092:9092
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers
    volumes:
      - ~/Desktop/h2/data/:/opt/h2-data/

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ~/Desktop/redis/data/:/data

  spring:
    container_name: spring
    image: yundol/syluv
    ports:
      - 8080:8080
    volumes:
      - /var/log/:/logs/
    depends_on:
      - redis
      - h2db
